version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: npm install yarn

  deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: changing pem file permissions
          commanf: chmod 400 nestjs_example.pem
      - run:
          name: connecting to ssh client
          command: ssh -i "nestjs_example.pem" ec2-user@ec2-13-235-42-133.ap-south-1.compute.amazonaws.com

workflows:
  build_nest:
    jobs:
      - build
      - deploy:
          requires:
            - build
