version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: npm install -g yarn
      - run:
          name: Installing AWS CLI
          command: |
            sudo yum update
            sudo yum install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: building
          command: yarn add && yarn run build

  deploy:
    docker:
      - image: cimg/node:15.1
    environment:
      host: 13.235.42.133
    steps:
      - checkout

workflows:
  build_nest:
    jobs:
      - build
      - deploy
