version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn add

workflows:
  build_nest:
    jobs:
       - build
