version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demo_blog
    steps:
      - checkout
      - run:
          command: npm install

workflows:
  build_nest:
    jobs:
      - build
